services:
  postgres:
    image: postgres:16
    container_name: wc_postgres
    environment:
      POSTGRES_USER: wc_user
      POSTGRES_PASSWORD: wc_pass
      POSTGRES_DB: wc_warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

